### ISSUE TITLE
Windows Phone 8.1 support

### ISSUE THREAD

**Issue by SBRK** [microsoft/angle#10]
Hello. Is WP8.1 support in the works ? I've managed to run the WinRT rotating cube example on Windows Phone 8.1 by tweaking the WinRT solution, but I would like to know if neat and clean out of the box WP8.1 support is coming, and if so how soon ?
Cheers.

**Comment by stammen** [comment]
Yes. Windows 8.1 support is happening later this month. Please check back in a few weeks.

**Comment by SBRK** [comment]
Great, thanks !

**Comment by JMLX42** [comment]
This is amazing news! SBRK and I are R&D engineers on the Minko 3D engine (http://minko.io/engine). It's a cross-platform 3D engine written in C++11. Right now we support Windows, Linux and OSX. In a few weeks - if not days - we will release a new beta with support for iOS and Android. We would love to have WP8.1 working!

Our first tests are very encouraging, since it seems all of our existing code, tutorials and examples should work out of the box on all the supported platforms AND WP8.1.

If you need some users to test and provide feedback/demos, please let us know!

**Comment by olivierbloch** [comment]
Hey Promethe42, this is great news! Any update on your port to Windows devices?
Feel free to let  us know if you are having issues and let's make some noise once you are live with Windows devices support!

**Comment by coopp** [comment]
If you want to experiment some more, we have a development branch https://github.com/MSOpenTech/angle/tree/future-dev which contains Windows 8.1 and Windows Phone 8.1 support.  This branch is actively being developed on and is currently taking changes from the latest google mainline ANGLE source.

**Comment by SBRK** [comment]
Great, thanks a lot !

**Comment by ghost** [comment]
implemented in future-dev branch. closing.
