### ISSUE TITLE
Question on triangle strips

### ISSUE THREAD

**Issue by doginthehole** [microsoft/angle#104]
Hi all, 

Please excuse the most likely very basic questions on triangle strips. I don't have any experience so far working with them and on reading up I've found that I should be using glBegin(gl_triangle_strip) to initialize them in open gl. However it looks to me like this isn't supported in the angle translator. Is there another way I should go about initializing them or is this not needed?

The next question is on loading in the strips, should I be using glBufferData to load in the entire array of strips or should I loop through them and use glBufferData for each strip?

Thanks for all of your help, this community is very supportive.

**Comment by austinkinross** [comment]
Hi there! glBegin is part of the OpenGL standard but isn't part of OpenGL ES. ANGLE only supports translating OpenGL ES -> D3D (and not OpenGL -> D3D), which is why you're not finding glBegin in ANGLE.

If you search online for 'GL_TRIANGLE_STRIP OpenGL ES' then you should find some tutorials and/or documentation explaining how to use them with OpenGL ES. For example, you could see Listing 8-2 of Apple's documentation on [this page ](https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html)

Without knowing specifics about your scenario, it's generally best to minimize the number of calls to upload data to the GPU.

Thanks,
Austin

**Comment by doginthehole** [comment]
Thanks a lot for the response and help Austin, I'll be looking into this today!
