### ISSUE TITLE
eglCreateWindowSurface fails for CoreWindow

### ISSUE THREAD

**Issue by mgrviper** [microsoft/angle#122]
eglCreateWindowSurface fails for CoreWindow with output

> windows\advcore\winrt\iwindow\corewindow\componenthelper.cpp(259)\Windows.UI.dll!0F0FAC93: (caller: 0F0F3112) ReturnHr\[PreRelease](1) tid(38e4) 88980800 DCOMPOSITION_ERROR_WINDOW_ALREADY_COMPOSED

inside HRESULT CoreWindowNativeWindow::createSwapChain() at 
>HRESULT result = factory->CreateSwapChainForCoreWindow(device, mCoreWindow.Get(), &swapChainDesc, nullptr, newSwapChain.ReleaseAndGetAddressOf());

eglCreateWindowSurface is successful if SwapChainPanel specified instead of CoreWindow.

attrib_list for eglCreateWindowSurface is 		

> EGL_ANGLE_SURFACE_RENDER_TO_BACK_BUFFER, EGL_TRUE,
 EGL_NONE

This is a first call to eglCreateWindowSurface and no SwapChains created explicitly.
Is there known differences in initializing angle for CoreWindow and SwapChainPanel?

**Comment by austinkinross** [comment]
Hi! 

Yes, you can't create a CoreWindow swapchain inside a XAML application. You're seeing the 'DCOMPOSITION_ERROR_WINDOW_ALREADY_COMPOSED' error because XAML has already taken ownership of the application's CoreWindow at that point, which blocks you from being able to create your own swapchain against the CoreWindow.

As a result, switching between CoreWindow and SwapChainPanel isn't as easy as switching parameters to eglCreateWindowSurface. You may want to take a look at our [Visual Studio templates](https://github.com/Microsoft/angle/tree/ms-master/templates), which include CoreWindow and SwapChainPanel/XAML templates for both Windows 8.1 and Windows 10.

Hope this helps,
Austin

**Comment by mgrviper** [comment]
Thank you for fast reply.
