### ISSUE TITLE
False positive resize detection in ms-holographic-experimental on fall creators update

### ISSUE THREAD

**Issue by mlfarrell** [microsoft/angle#126]
@MikeRiches 

This if-statement is true every frame, causing the graphics driver to flip out and recreate rendering buffers each frame and flicker the headset like crazy since it never properly renders the frame:

HolographicSwapChain11.cpp:

`
        // Don't resize unnecessarily

        if (mBackBufferTexture != spCameraBackBuffer)
`

is there a more robust way to detect this resize necessity?

**Comment by mlfarrell** [comment]
Here's what I had to do. 

`

		BOOL IsEqual(ID3D11Texture2D *pTexture1, ID3D11Texture2D *pTexture2)
		{
		  IUnknown *u1, *u2;

		  if(!pTexture1 || !pTexture2)
			return FALSE;

		  //this honestly must be a bug in win SDK
		  //for now this this the best I can do...
		  D3D11_TEXTURE2D_DESC desc1, desc2;

		  pTexture1->GetDesc(&desc1);
		  pTexture2->GetDesc(&desc2);

		  return (desc1.Width == desc2.Width && desc1.Height == desc2.Height);
		}
`

I'm experiencing ALOT of other problems on my acer though, namely serious flickering.  any help would be appreciated.

**Comment by MikeRiches** [comment]
@mlfarrell: I would actually put it back. As of the Creator's Update, the swap chain implementation exposed to holographic apps returns a different buffer each frame - so the RTV and SRV do need to get recreated, and that is part of what this code does in HolographicSwapChain11.cpp.

We shouldn't have to recreate offscreen buffers for each back buffer in the rotation - I would move that part inside the size-change check.

The flickering should be fixed by removing the calls to DiscardView.

**Comment by mlfarrell** [comment]
Yes I realized that after the fact.  I'll close this ticket and update on the other one.  I notice flashing wild colors when I put it back as it was before, and just black flickering when I do the IsEqual test.  Lets see if fixing the discard view fixes the flickering for either case.
