### ISSUE TITLE
Missing lib

### ISSUE THREAD

**Issue by cjd22** [microsoft/angle#152]
I am creating AppForOpenGlEs with the template. I install angle from Nuget but when I build the project I get the error "fatal error LNK1104: cannot open file '\..\winrt\10\src\Debug_Win32\lib\libGLESv2.lib'. This an out of the box template. Does anyone have any idea what is happening. Thanks in advance

**Comment by austinkinross** [comment]
Hi there, the templates in this repository assume that you've built ANGLE yourself from this repository instead of using the NuGet package. As a result, you'll need to remove the relevant lines from your project files before you can use the NuGet package. 

That shouldn't be too hard though. Try deleting these lines from your .vcxproj:

```
<PropertyGroup Label="ANGLE">
  <AngleIncPath Condition=" '$(AngleIncPath)' == '' ">$(AngleRootPath)\include\</AngleIncPath>
  <AngleBinPath Condition=" '$(AngleBinPath)' == '' ">$(AngleRootPath)\winrt\10\src\$(Configuration)_$(Platform)\</AngleBinPath>
</PropertyGroup>
```

and then remove any remaining usage of 'AngleIncPath' or 'AngleBinPath', e.g by changing this

```
  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32'">
    <Link>
      <AdditionalDependencies>$(AngleBinPath)lib\libGLESv2.lib; $(AngleBinPath)lib\libEGL.lib; mincore.lib; %(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories); $(VCInstallDir)\lib\store; $(VCInstallDir)\lib</AdditionalLibraryDirectories>
    </Link>
  </ItemDefinitionGroup>
```

into this:
```
  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32'">
    <Link>
      <AdditionalDependencies>mincore.lib; %(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>%(AdditionalLibraryDirectories); $(VCInstallDir)\lib\store; $(VCInstallDir)\lib</AdditionalLibraryDirectories>
    </Link>
  </ItemDefinitionGroup>
```

Hope this helps.

**Comment by cjd22** [comment]
Thanks.
