### ISSUE TITLE
Enable instancing on Windows Phone

### ISSUE THREAD

**Issue by amerkoleci** [microsoft/angle#16]
I've saw in one of your commit you've removed instancing for feature level 9.3, I think this should be handled soon as most code probably depends of this feature.

Thanks,
Amer

**Comment by austinkinross** [comment]
Hi Amer, 

Thanks for the feedback. Adding support for instancing on 9.3 is high on our list of priorities. We had to restrict instancing on 9.3 due to hardware limitations, but we understand the limitations and believe we can work around them. We plan to investigate this further in the near future.

Thanks again,
Austin

**Comment by amerkoleci** [comment]
Windows Phone 8.1 supports hardware instancing so its not limitation to hardware.

Thank you for feedback,
Amer

**Comment by austinkinross** [comment]
You're correct, 9.3 hardware does supports instancing. However, the first input in the InputLayout (equivalent to an "attribute" in OpenGL ES) must contain per-vertex data, and not per-instance data. 

As a result, ANGLE needs to know which attributes are per-vertex and which are per-instance when it creates/compiles its D3D shaders. This is not the case in OpenGL ES, where apps can set attributes to be per-instance (via glVertexAttribDivisor) _after_ creating/compiling their shaders.

We're aware of these problems and will investigate soon.

Thanks,
Austin

**Comment by austinkinross** [comment]
Hi Amer, we've just added support for instancing on Feature Level 9.3! It should now work unconditionally on any Windows Phone.
