### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by mattleibow** [microsoft/angle#162]
HI folks, I just wanted to check what the status of this project is?

I see Google has been going on their merry way with their fork: https://github.com/google/angle

Should I be using this? Are any changes being upstreamed?

**Comment by austinkinross** [comment]
I recommend using this version of ANGLE if you're creating a UWP (Universal Windows Platform) app. For anything else, I recommend using Google's version.

Microsoft has made a lot of changes to ANGLE in the past, and the changes have been upstreamed to master. Unfortunately, since then, UWP support has been broken in master after it moved over to a new project generation system (GN). This means that we can't merge master as-is into Microsoft/ANGLE without breaking UWP support.

We'd like to fix UWP support in master at some point, but that won't happen in the near future.

Thanks!

**Comment by mgrviper** [comment]
@austinkinross Is any work planned for this fork of ANGLE in the foreseeable future? As it seems project currently stalled with no active maintaining. Is it considered "done"?

**Comment by austinkinross** [comment]
Hi, yes -- all of our changes have been pushed upstream to the master ANGLE repository, so our work in this repository is now done.

As of today, the master ANGLE repository can be used to build for UWP again, so we recommend that everyone moves over to use that repository going forwards.

Thanks
Austin
