### ISSUE TITLE
Xbox One 

### ISSUE THREAD

**Issue by brunotrevisan** [microsoft/angle#171]
On the Xbox One the screen is black, I read here on a problem that was fixed in the update but I still can't get it to work on the Xbox One, the screen is black but when minimizing the game I see the image in the background, does anyone have a solution?

I believe it is the vertex of the shaders but I do not know how to solve

**Comment by austinkinross** [comment]
Hi, I recommend asking your questions over on the main ANGLE discussion group, since you're likely to get a better response there. This repository has been deprecated for years (after we submitted all of its changes to the main ANGLE repo), and I haven't personally worked on ANGLE since then. 

IIRC the Xbox One SRA only supports Feature Level 10_0, which prevents it from fully supporting GLES 3.0. I suspect that might be related to your issue.
