### ISSUE TITLE
Enable Direct2D and DirectWrite interop

### ISSUE THREAD

**Issue by amerkoleci** [microsoft/angle#19]
Allow access to native DXGI and D3D resources, so integration with Direct2D and DirectWrite would be possible, I would use libraries like (https://github.com/Microsoft/Win2D), probably you need to create device with BGRA flags.

**Comment by austinkinross** [comment]
We plan to investigate interop between ANGLE and other D3D-based libraries in the future. This isn't an easy problem to solve, since we'd have to prevent the other libraries from altering ANGLE's D3D resources and states in unexpected ways, which could lead to unexpected behavior.

In the meantime, you can use Win2D and ANGLE separately in the same XAML app, but not Win2D interop'ing with ANGLE. Win2D and ANGLE would have to use separate XAML elements.

**Comment by austinkinross** [comment]
Hi, we've written a wiki page explaining how to interop ANGLE with other DirectX content. The page is available here: https://github.com/MSOpenTech/angle/wiki/Interop-with-other-DirectX-code

The page even includes a screenshot of interop between ANGLE and Win2D, as you mentioned. Feel free to let us know if you try to interop ANGLE with Win2D (or other DirectX content)- we'd be interested to hear about your experiences.

Thanks!
