### ISSUE TITLE
No Landscape support in "App for OpenGL ES" (UniversalCoreWindow) template

### ISSUE THREAD

**Issue by pulcheri** [microsoft/angle#25]
The triangle is always rendered in portrait mode on WP8.1 even when:
a) Landscape is selected in Package.appxmanifest
and/or
b)

```
    DisplayInformation::AutoRotationPreferences = Windows::Graphics::Display::DisplayOrientations::Landscape;
```

called in 'App::SetWindow(CoreWindow^ window)'

(XAML version supports landscape just fine)

Tested on Lumia 520

**Comment by austinkinross** [comment]
Hi montonero. Yes, it looks like there's a bug here. Our team is running light for the next couple of days due to office moves, but we will hopefully be able to investigate next week.

In the meantime, if you need to workaround this then you can try modifying ANGLE to call "newSwapChain->SetRotation(DXGI_MODE_ROTATION_ROTATE270);" at the end of "CoreWindowNativeWindow::createSwapChain" in /src/common/winrt/CoreWindowNativeWindow.cpp. You should then rebuild ANGLE, and rebuild your app (to force it to copy the new ANGLE binaries).

**Comment by pulcheri** [comment]
Thanks, Austin. I can confirm that proposed workaround works for now.

**Comment by pulcheri** [comment]
Hi, just wondering if there is an ETA on a proper fix?

**Comment by austinkinross** [comment]
Hi, apologies for not getting back to you on this one! 

We've decided not to support "Landscape" mode in the UniversalCoreWindow template. The workaround I suggested above (using IDXGISwapChain1::SetRotation()) is expensive performance-wise, and we'd like to discourage its usage. If you wish to use "Landscape" mode then we recommend using the XAML (UniversalSwapChainPanel) template.

Note that it's still possible to author a UniversalCoreWindow app that can be used in a landscape manner (i.e. with the phone on its side), but it will be the app's responsibility to render all of its content in the correct position/orientation.

My colleague @coopp helped investigate this, but he is currently on vacation.

**Comment by austinkinross** [comment]
To clarify the status of landscape/rotation support:
- All Windows 10 templates (XAML and CoreWindow) support landscape and rotation on all platforms
- The Windows Phone 8.1 XAML template supports landscape and rotation
- The Windows 8.1 CoreWindow template supports landscape and rotation
- The Windows Phone 8.1 CoreWindow template does not support landscape or rotation. Please use one of the other templates if you require either of these.

Thanks!
