### ISSUE TITLE
Failed WACK tests

### ISSUE THREAD

**Issue by vasyaPP** [microsoft/angle#30]
Hi. I'm using ANGLE in my game for windows store and targetting to 8.1 version. Yesterday I tried to create app package and perform tests and got two errors.

> Direct3D Feature Test
> 
> FAILED
> Direct3D feature level support
> Error Found: The Direct3D feature level support test detected the following errors:
> Impact if not fixed: Windows Store requires all applications using Direct3D to render properly on feature level 9_1. See the following link for more information:
> Certification requirements for Windows apps
> How to fix: Ensure that your app renders correctly on Direct3D feature level 9_1, even if you expect it to run at a higher feature level. See the following link for more information:
> Developing for different Direct3D feature levels
> 
> FAILED
> Direct3D Trim after Suspend
> Error Found: The Direct3D Trim after Suspend test detected the following errors:
> Impact if not fixed: If the app does not call Trim on its Direct3D device, the app will not release memory allocated for its earlier 3D work. This increases the risk of apps being terminated due to system memory pressure.
> How to fix: The app should call the Trim API on its IDXGIDevice3 interface anytime it is about to be suspended.
> More Information
- Direct3D feature level support

I have found, that there are no support in angle code for feature versions lower 9_3. So I'm not sure what I shoult to do..
- Direct3D Trim after Suspend

I also found in code, that there is place for invoking Trim. So I'm puzzled again.

Can you help me to understand how to fix them?

**Comment by austinkinross** [comment]
Hi vasyaPP,

Regarding the feature level support: could you update your app's EGL initialization code to match our latest Visual Studio templates? If the hardware GPU doesn't support 9_3 then we use a software rasterizer (WARP), but we recently changed how ANGLE/the templates configure WARP. 

Regarding the call to Trim(): I couldn't reproduce this problem on our latest version of ANGLE. Could you try updating to the latest version of our branch, and see if your issue is fixed?

Let me know if you still have problems,
Austin

**Comment by vasyaPP** [comment]
Hi, thanks for reply. I have forgot, that I failed launch tests on my dev pc. Today I have tested app on another pc and passed tests successfully. Sorry for this misunderstanding. And thanks for your work. You guys are awesome!
