### ISSUE TITLE
ARM perfomance

### ISSUE THREAD

**Issue by vasyaPP** [microsoft/angle#32]
Hi. I'm porting existing game to windows store (win 8.1) and have problems with low performance on arm devices (Surface tablets). My game shows about 3-5 fps, I'm still searching problem. But I would like to ask a question, are there any known problems with performance on arm devices? I have found same thread on cocos2d-x forums (I'm not using cocos2d-x). 
My game runs good on x86-x64 Surface tablets btw.

**Comment by amerkoleci** [comment]
Did you run debug version of angle?

**Comment by vasyaPP** [comment]
No, I'm using release dll. I have checked it just now and my angle dll's are linked to msvcp120_app.dll, not msvcp120d_app.dll.

**Comment by vasyaPP** [comment]
I have found, that eglSwapBuffers(mEglDisplay, surface) takes over 100ms (average 125-150ms) in both release and debug configurations of my game.

**Comment by austinkinross** [comment]
Hi vasyaPP!

The problems you’re experiencing are likely to be related to the D3D Feature Level used by these devices rather than their architecture. The hardware GPUs in Surface RT tablets run at D3D Feature Level 9_1, while Surface Pros support Feature Level 11_0+.

ANGLE doesn't currently support Feature Level 9_1 or 9_2, because we would only be able to offer a limited subset of OpenGL ES 2.0 functionality on these devices. If ANGLE is run on a 9_1 or 9_2 device such as the Surface RT then it switches to using WARP, a D3D11 software rasterizer which supports Feature Level 11_0+. This allows us to offer full OpenGL ES 2.0 functionality, but the lack of hardware acceleration can hurt performance.

We are currently considering supporting a limited version of OpenGL ES 2.0 on Feature Level 9_1 or 9_2, but we haven't committed to this yet. If you feel that your app's performance on Feature Level 9_1 devices is too poor to release, then my current recommendation is that you restrict your app's release to devices that support Feature Level 9_3 or above.

Please note: all Windows Phone devices support Feature Level 9_3 (or above), so they will not be affected by this issue.

Thanks,
Austin

**Comment by vasyaPP** [comment]
Hi austinkinross, thanks for great explanation. Glad to hear, that windows phone devices should work without any problems of this kind.
