### ISSUE TITLE
Unable to index uniform at runtime

### ISSUE THREAD

**Issue by jiangcaiyang** [microsoft/angle#35]
The shader which is fully compatible on OpenGL ES 2.0 does not work on ANGLE compatible Windows Phone devices. I'm using Qt for my app development.

The shader are listed:
# ifdef GL_ES

precision highp float;
# endif

attribute float b1Index;
attribute float b2Index;

uniform vec3 value[256];

void main( void )
{
    int b1 = int(b1Index);
    gl_Position = vec4( value[b1], 1.0 );
}

The fragment shader are even simpler for test:

void main(void)
{
    gl_FragColor = vec4( 1.0, 1.0, 0.0, 0.0 );
}

The problem mainly on "value[b1]", but it is okay to run this shader on Android.

**Comment by austinkinross** [comment]
Hi, thank you for reporting this! 

Could you describe the behavior that you see when you try to use this shader? e.g. does the shader not compile? Do you see rendering corruption?

Thanks,
Austin

**Comment by jiangcaiyang** [comment]
The D3D shader does not compile. Currently tested on Windows Phone 8.1( Lumia 530 ).
When I turn to IRC for help, the ANGLE maintainers ( maybe relevant developers ) told me that I'm using the old version of ANGLE, the new version support dynamic index uniform at runtime. I'm continuing to concern on this.

**Comment by jiangcaiyang** [comment]
![My Window Phone 8.1](http://i1288.photobucket.com/albums/b485/jiangcaiyang/wp_ss_20150417_0001_zpsxbptmxqu.png)

**Comment by austinkinross** [comment]
Hi,

Looking more closely at this, I believe your issue is because you are using too many uniforms in the shader here: "uniform vec3 value[256];".

You should query the OpenGL ES implementation to see how many uniforms it supports like this:

```
int maxUniformVectors;
glGetIntegerv(GL_MAX_VERTEX_UNIFORM_VECTORS, &maxUniformVectors);
```

ANGLE on D3D11 Feature Level 9_3 (e.g. on a Windows Phone) currently returns 255 for GL_MAX_VERTEX_UNIFORM_VECTORS, but it should return 252 (we'll fix this in the future).

Therefore, to solve your compilation issues, you should use 252 or fewer uniforms in your shader.

Hope this helps,
Austin
