### ISSUE TITLE
Strange behavior of template project after changing of orientation on mobile phone.

### ISSUE THREAD

**Issue by Umkerius** [microsoft/angle#41]
I compile template project and run it on Nokia Lumia 735 with Windows 10 on board.
I saw this: 
![img_20150628_185023](https://cloud.githubusercontent.com/assets/7581547/8397151/65f32fa8-1dca-11e5-88b7-3e69eed72f2f.jpg)
Then I rotated the phone and it changed screen orientation:
![img_20150628_190620](https://cloud.githubusercontent.com/assets/7581547/8397155/92457a70-1dca-11e5-8936-46c3f0cdab66.jpg)

How can I fix it?

**Comment by stammen** [comment]
You are probably using the CoreWindow template which does not handle rotation. Please use the XAML template if you want rotation to be handled for you automatically. For more info, please refer to:

https://github.com/MSOpenTech/angle/wiki/Choosing-a-Visual-Studio-template

**Comment by austinkinross** [comment]
Hey Umkerius! Yes, please use the XAML template if you need rotation to be handled correctly today on Windows 10.

The Windows 10 CoreWindow templates do support rotation, but CoreWindow rotation is currently handled differently across different versions of the Windows 10 Insider Preview (e.g. your Lumia 735 will handle it differently to a Surface Pro 3) which results in the bug you see. I expect this to be fixed in the future. We will ensure that rotation in the CoreWindow template works correctly on all of these devices once they handle CoreWindow rotation in the same way.

Thanks!
Austin

**Comment by Umkerius** [comment]
Thank you for answer! I will use a XAML template
