### ISSUE TITLE
Support for OES_EGL_image_external extension

### ISSUE THREAD

**Issue by vuhuy** [microsoft/angle#47]
Currently, the [OES_EGL_image_external extension](https://www.khronos.org/registry/gles/extensions/OES/OES_EGL_image_external.txt) does not seems to be supported by this branch of ANGLE. I have recently compiled ANGLE directly from this GitHub repository on the 17th of August, 2015.

Here is an example of a shader which uses the OES_EGL_image_external extension:

```
#extension GL_OES_EGL_image_external : require
precision mediump float;
varying vec2 vTextureCoord;
uniform samplerExternalOES  sTexture;

void main() {
    gl_FragColor = texture2D(sTexture, vTextureCoord);
}
```

I am loading this shader by declaring it as `const std::string` and passing it to `CompileProgram(GLenum type, const std::string &source)` (as provided within the XAML App for OpenGL ES template). When using this GLSL shader in a Windows Store App, the app will crash with the following exception:

```
WinRT information: Shader compilation failed: ERROR: 0:1: 'precision' : unexpected token`
WARNING: 0:1: '' : unexpected end of file found in directive
ERROR: 0:? : '' : syntax error
```

Note that the exception does not mention the extension-directive, but rather mentions the next line in the shader.

I have found the following line in `src\libANGLE\renderer\d3d\CompilerD3D.cpp(46)`:

```
mResources.EXT_shader_texture_lod = 1;
// resources.OES_EGL_image_external = mRenderer->getShareHandleSupport() ? 1 : 0; // TODO: commented out until the extension is actually supported.
mResources.FragmentPrecisionHigh = 1;   // Shader Model 2+ always supports FP24 (s16e7) which corresponds to highp
```

This would indicate you are not supporting this extension yet. However, it seems like this extension is already (partially) supported by the MSOpenTech version of ANGLE, and might by fully supported in other branches of the ANGLE project (but I have not verified this statement yet). I am currently not aware of the status of this extension, as I could not find a road map for this project. I would be very happy if you can give an update about the status of implementing this extension (or fixing the bug, whatever is appropriate). Thank you.

**Comment by austinkinross** [comment]
Hi vuhuy,

You're correct, GL_OES_EGL_image_external isn't currently available in ANGLE. The folks at Google are working on adding support for EGL Image extensions but they haven't completed that work yet. By coincidence, they posted a code-review for the D3D9 and D3D11 implementations of GL_OES_EGL_image this morning [here](https://chromium-review.googlesource.com/#/c/295152/).

I believe Google plan to add support for GL_OES_EGL_image_external and GL_OES_EGL_image_external_essl3 in the future, but I don't know when. If you are keen to find out then you could post a question [here](https://groups.google.com/forum/#!forum/angleproject).

Since we regularly merge Google's ANGLE branch with our ANGLE branch, any implementation added to Google's branch will be available in our branch shortly afterwards.

Let me know if you have any other questions,
Austin

**Comment by austinkinross** [comment]
Hi vuhuy,

Support for OES_EGL_image_external and OES_EGL_image_external_essl3 was recently added to the master ANGLE repository, and we have just merged the change into the ms-master branch here on GitHub.

https://github.com/Microsoft/angle/commit/b66a9097a33d8a94a158815d7b684ae6570ee5d4

Thanks!
