### ISSUE TITLE
D3D11 device is removed on multiple calls to glFinish()

### ISSUE THREAD

**Issue by gargvineet** [microsoft/angle#52]
Hi,
In our app we are calling glFinish() multiple times to keep textures on CPU and GPU in sync. But at a particular time, it just removes the device and we have to restart the app. Any help or what could be going wrong?
Thanks
Vineet Garg

**Comment by coopp** [comment]
Hi gargvineet,
This sounds like the graphics driver has crashed and the device is being removed.
Are you calling glFinish( ) every frame or just periodically?  Could you provide the following info so we can help narrow down what is going on?
- Operating System
- Devices are you seeing this issue on.  Phone? PC?
- NuGet verision/build of ANGLE

We will try to repro the issue here, but may need more details to match your configuration.  Any additional information would be great.
Thanks,
Cooper

**Comment by gargvineet** [comment]
We are not calling glFinish on every frame, but yes the frequency is a bit high.
Following is the config:
OS: WINDOWS 10
DEVICE: DESKTOP
Nuget: 2.1.5

Another thing I have two devices with same config and only difference is that one has default GPU driver of Microsoft and the other has the AMD one, the one with MS DRIVER works fine. But the issue is coming on two other devices as well, which have different GPUs.

-Vineet Garg

**Comment by coopp** [comment]
Hi Vineet,
  This is very likely to be a bug in the graphics driver.  I am still trying to repro the issue here.  If you have a simple repro sample I can look deeper into this.  If this is a driver bug, updating to the latest graphics drivers may help on the machines that are experiencing the device lost conditions.

**Comment by gargvineet** [comment]
hi I have the latest drivers on all the machines on which I am facing the issue. Could this be related to making GL/Angle calls on background threads? Another query, Should we make GL calls( using ANGLE) on background threads Or not?

**Comment by austinkinross** [comment]
Hi gargvineet! Yes, the issues you're seeing are likely to be related to you using ANGLE on background threads.

ANGLE, like most OpenGL implementations, doesn't support using the same OpenGL/EGL context on multiple threads simultaneously. Additionally, with ANGLE you should make your GL calls on the same thread that you used to initialize your OpenGL/EGL context.

Hope this helps!
Austin

**Comment by austinkinross** [comment]
I'm closing this issue since I think the questions have been answered. Please feel free to reactivate if you have any further questions!
