### ISSUE TITLE
texture smoothing works bad

### ISSUE THREAD

**Issue by salos1982** [microsoft/angle#57]
Hi, I do not know why but I have troubles with smoothing textures.
It seems that result of using GL_NEAREST and GL_LINEAR is almost the same. There are a lot of artefacts on edges.
Windows Phone GL_LINEAR
![wp_linear](https://cloud.githubusercontent.com/assets/2404581/13073695/25c8ec3a-d4b1-11e5-968a-a22b81abf17d.png)
Windows Phone GL_NEAREST
![wp_nearest](https://cloud.githubusercontent.com/assets/2404581/13073698/2a6b247e-d4b1-11e5-8c8f-be4344b6d821.png)
Android GL_LINEAR
![android_linear](https://cloud.githubusercontent.com/assets/2404581/13073705/3959eba0-d4b1-11e5-80c5-a1c0c2deed3d.png)

I added screenshot from my game from windows phone (Lumia 550) for all textures with GL_LINEAR min and mag filter. And also I attached screenshot from Android device (Galaxy S3) with the same resulution. The use the same code except the windows phone version has DXT compression (but without compression result is the similar)

**Comment by stammen** [comment]
@salos1982 The problem is that the Angle template code using by cocos2d-x is not rendering at the full screen resolution of the device (this happens mainly with the Windows Phone. This is due to the fact that rendering in full screen resolution could cause a drop in FPS.

Please try the following:

1) In Cocos2dEngine\OpenGLESPage.xaml.cpp add the following around line 154

void OpenGLESPage::CreateRenderSurface()
{
    if (mOpenGLES && mRenderSurface == EGL_NO_SURFACE)
    {
        // The app can configure the the SwapChainPanel which may boost performance.
        // By default, this template uses the default configuration.
        //mRenderSurface = mOpenGLES->CreateSurface(swapChainPanel, nullptr, nullptr);

```
    Windows::Graphics::Display::DisplayInformation^ info = Windows::Graphics::Display::DisplayInformation::GetForCurrentView();
    auto screenResolutionScale = info->LogicalDpi / 96.0f;

    // You can configure the SwapChainPanel to render at a lower resolution and be scaled up to
    // the swapchain panel size. This scaling is often free on mobile hardware.
    //
    // One way to configure the SwapChainPanel is to specify precisely which resolution it should render at.
    // Size customRenderSurfaceSize = Size(800, 600);
    // mRenderSurface = mOpenGLES->CreateSurface(swapChainPanel, &customRenderSurfaceSize, nullptr);
    //
    // Another way is to tell the SwapChainPanel to render at a certain scale factor compared to its size.
    // e.g. if the SwapChainPanel is 1920x1280 then setting a factor of 0.5f will make the app render at 960x640
    mRenderSurface = mOpenGLES->CreateSurface(swapChainPanel, nullptr, &screenResolutionScale);
    // 
}
```

}

2) In libcocos2d/platform/winrt/cocos2dCCGLViewImpl-winrt.h add the following around line 190

```
float m_screenResolutionScale;
```

3) In lib/platform/winrt/cocos2dCCGLViewImpl-winrt.cpp add the following around line 94

```
, m_screenResolutionScale(1.0f)
```

4) In libcocos2d/platform/winrt/cocos2dCCGLViewImpl-winrt.cpp add the following around line 131

```
m_screenResolutionScale = m_dpi / 96.0f;
```

4) In libcocos2d/platform/winrt/cocos2dCCGLViewImpl-winrt.cpp change the following around line 557

```
float x = p.X * m_screenResolutionScale;
float y = p.Y * m_screenResolutionScale;
returnValue = Vec2(x, y);
```

You may see a drop in FPS since the ANGLE is now pushing a lot more pixels to the screen. Please let me know if this improves the quality of your textures and we can work together to get these changes into cocos2d-x.

**Comment by stammen** [comment]
@salos1982 If you are not using cocos2d-x take a look at:

https://github.com/MSOpenTech/angle/wiki/Scaling-your-app-to-run-at-different-resolution-on-the-device

You should be able to figure out the needed changes to your ANGLE template code. Make sure you also scale your pointer coordinates as shown in the previous comment. Please let me know if you need any more help.

**Comment by salos1982** [comment]
thanks a lot. Your tip helps. It was not obvious

**Comment by stammen** [comment]
@salos1982 Glad to hear it is working better for you. Were you using cocos2d-x or just ANGLE?

**Comment by salos1982** [comment]
I'm using just angle, not cocos2d-x

**Comment by luyikk** [comment]
Why angle call DX11 very bad?
