### ISSUE TITLE
Problems with Alpha Rendering

### ISSUE THREAD

**Issue by dsokhryakov** [microsoft/angle#58]
Hi, something wrong in the latest version of angle. Could' you help me with this?
Microsoft released Update 1 for Windows 10 -  10.0.10586, and after that we have problems with alpha channel in our game. Only for Windows 10 Update 1, without update 1 - alpha  channel works good(On Windows 8.1 - good). Now, We downgrade version of Angle-project for normal render. 
We use cocos2d-x, Win10 angle template.
Wrong rendering:
![Wrong](http://i.imgur.com/jbT6ew4.png)
Good rendering:
![Wrong](http://i.imgur.com/D1N2LDa.png)

**Comment by austinkinross** [comment]
Hi, thanks for reporting your issue.

Could you please do two things to help us understand the issue here?

1) On your Windows 10 PC that has the rendering issue, could you press WinKey+R, then type "dxdiag", then click 'OK', then click "Save All Information..." and share the outputted text file?

2) You said that you "downgrade(d) version of Angle-project for normal render" - could you list exactly which versions of ANGLE you've tried, and on which versions of Windows you've tried them, and whether each combination shows the rendering issue in your screenshot? For example, you could create a list like this:
- Windows 10 version XXXXX, ANGLE version X.X.X - has rendering issue
- Windows 10 version XXXXX, ANGLE version X.X.X - renders correctly
- Windows 10 version XXXXX, ANGLE version X.X.X - renders correctly
- Windows 8.1, ANGLE version X.X.X - renders correctly

Thanks!
Austin

**Comment by dsokhryakov** [comment]
1) I have problem not only on my PC. Any PC/tablets with OS Win10 (10586) have same problem with rendering. The same devices without Update 1(10586) worked good with the same version angle.
2) I don't know the Number of commit, but GL_VERSION show -`OpenGL ES 2.0 (ANGLE 2.1.0.badf00dbad00)`. How to find out version of ANGLE, If i have only .lib and .dll files?

Windows 10 build 10240 , ANGLE version(last commit  449ef15) - renders correctly
Windows 10 build 10586 , ANGLE version(last commit  449ef15) - has rendering issue
Windows 10 build 9600,  ANGLE version(last commit  449ef15) - renders correctly

**Comment by austinkinross** [comment]
Thanks for the update! For further investigation I think we'll need a way of reproducing the issue here. Are you able to share your app with us? Is it available in the Windows Store?

Alternatively, if you're using Visual Studio to write your application, could you try using Visual Studio Graphics Diagnostics to capture a graphics trace of your app, save it to a *.vsglog file, and share the .vsglog file with us? 

Instructions for Visual Studio Graphics Diagnostics are available at this link: https://msopentech.com/blog/2014/10/30/graphics-diagnostics-formerly-pix-and-opengl-es-via-angle

Thanks again for reporting your issue!

**Comment by dsokhryakov** [comment]
Link to .vsglog file is here: http://1drv.ms/1VJVl0s
When Render Texture creates the screenshot in game, we can see good renders. Graphics trace shows normal picture too.

**Comment by austinkinross** [comment]
Just a quick update: thanks a lot for uploading the .vsglog file! Unfortunately I haven't been able to reproduce this issue locally on my PC yet, but I'm going to keep trying. I'll let you know how it goes.

In the meantime, if you're able to create a standalone app that reproduces this issue and can send it to me, then that would be extremely helpful.

Thanks,
Austin

**Comment by stammen** [comment]
@dsokhryakov  cocos2d-x is currently using Angle commit 0edf96a, It has not yet been updated/tested with commit 449ef15. Do you get this problem using the Angle DLL's that ship with cocos2d-x?

**Comment by dsokhryakov** [comment]
> Do you get this problem using the Angle DLL's that ship with cocos2d-x?

Yes, I have . 

>  if you're able to create a standalone app that reproduces this issue and can send it to me, then that would be extremely helpful.

I'll prepare build for you.

**Comment by diamond-msc** [comment]
@dsokhryakov Why did you close the issue?

I see the same, or a related, issue.
Alpha-non-premultiplied sprites are rendered with a white tint, on pixels where alpha is neither 0 nor 1.

Modified `HelloWorldScene.cpp` of the cocos2d-x `cpp-empty-test` (@stammen):

``` c++
#include "HelloWorldScene.h"
#include "AppMacros.h"

USING_NS_CC;

Scene* HelloWorld::scene()
{
    auto scene = Scene::create();
    HelloWorld *layer = HelloWorld::create();
    scene->addChild(layer);
    return scene;
}

bool HelloWorld::init()
{
    if ( !Layer::init() )
    {
        return false;
    }

    auto visibleSize = Director::getInstance()->getVisibleSize();
    auto origin = Director::getInstance()->getVisibleOrigin();

    const int PX = 256;
    Color4B _data[PX][PX];
    for (int x = 0; x < PX; x++) {
      for (int y = 0; y < PX; y++) {
        auto r = (Vec2(x, y) / (PX - 1) - Vec2(0.5, 0.5)).length() * 2;
        auto o = std::min(std::max(0.0f, float(1 - pow(r, 2))), 1.0f) * 255;
        _data[x][y] = { 0, 0, 0, (unsigned char)o };
      }
    }

    auto texture = new Texture2D;
    texture->initWithData(_data, PX * PX * 4, Texture2D::PixelFormat::RGBA8888, PX, PX, { float(PX), float(PX) });

    auto sprite2 = Sprite::createWithTexture(texture);
    sprite2->setColor({ 0, 0, 0 });
    this->addChild(sprite2);
    sprite2->setPosition(Vec2(visibleSize / 2) + origin);

    return true;
}
```

Screenshot:
![snip](https://cloud.githubusercontent.com/assets/3754448/14770566/ef387740-0a74-11e6-9438-c770452e4ac2.PNG)

Expected: Only black. No grey halo.

DxDiag: https://gist.github.com/diamond-msc/7290a0c8a9ee7d5b3d4182a1b7fcc9b9

**Comment by dsokhryakov** [comment]
@diamond-msc  Hi. Change Color theme of XAML Page, change and set your background color of Page to BLACK. It's answer from support of Microsoft. You can reproduce this bug on windows 10 mobile, just switch the OS theme from black to white.

**Comment by diamond-msc** [comment]
@dsokhryakov thanks.
@stammen I don't know if this is an angle issue in the first place, but adding this to `OpenGLESPage.xaml.cpp` fixed my cocos2d-x app:
`Background = ref new SolidColorBrush(Windows::UI::Colors::Black);`

**Comment by stammen** [comment]
@diamond-msc 

Another way to accomplish this is with XAML:

``````
````XML
<Page
    x:Class="Breakout.OpenGLESPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Breakout"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Background="Black"
    mc:Ignorable="d">

    <SwapChainPanel x:Name="swapChainPanel">
    </SwapChainPanel>
</Page>
````
``````
