### ISSUE TITLE
XBox One rendering

### ISSUE THREAD

**Issue by BurkeyCode** [microsoft/angle#60]
I just setup Dev Mode on my retail XBox and am testing it out, I have been able to deploy and run a DX app without issue however a simple Angle project does not render.

glClear works and clears to the correct colour, the shader appears to compile and it runs, hits breakpoints and there are no errors but nothing is rendered on screen.

This is just the default Cross Platform ES app in VS2015.

**Comment by austinkinross** [comment]
Hi, thanks for reporting the issue! We can reproduce it and are investigating it.

In the meantime, could you try using WARP (a software rasterizer for DirectX) instead of the hardware GPU? You can do this by changing the following line in App.cpp in the WindowsUniversal.Application project:
`mEglDisplay = eglGetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, EGL_DEFAULT_DISPLAY, defaultDisplayAttributes);`

To this:
`mEglDisplay = eglGetPlatformDisplayEXT(EGL_PLATFORM_ANGLE_ANGLE, EGL_DEFAULT_DISPLAY, warpDisplayAttributes);`

This will run more slowly than using the hardware GPU, but it should work and unblock you until we understand the issue more thoroughly.

Thanks,
Austin

**Comment by stevetranby** [comment]
I was able to get the template rotating cube to run on my XBox in dev mode by changing to use the warpDisplayAttributes. Hope you guys figure out the issue so we can run games on the GPU soon :D

**Comment by RustyMoyher** [comment]
I'm seeing the same issues as above, but I was able to get the basic [Cocos2D-X](https://github.com/cocos2d/cocos2d-x) hello world project running now on my Xbox One with ANGLE using warpDisplayAttributes.

**Comment by austinkinross** [comment]
Hi all, the fix to this will be part of the future OS update that will bring UWP support to the general public, and may be part of future pre-release OS updates for developers.

In the meantime, please continue to use WARP for development, and then switch over to the hardware GPU when the OS update is released. I'll update and close this thread when a OS update is released that supports ANGLE using the hardware GPU.

Thanks a lot for your patience,
Austin

**Comment by austinkinross** [comment]
Hi, the fix for this is available in the Windows 10 Anniversary Update, which was released to the general public a few weeks ago. 

I can confirm that the Cross Platform OpenGL ES template works on the hardware GPU, and Cocos2D-X should too.

Thanks for all of your interest in this!

**Comment by pinguin999** [comment]
@austinkinross Where can I find the Cross Platform OpenGL ES template?

**Comment by austinkinross** [comment]
This is the template: https://marketplace.visualstudio.com/items?itemName=MarianLuparuMSFT.VisualCOpenGLES2ProjectTemplate

The template was lasted updated on 11/3/2015. You may need to fix some issues with it before it will work with recent SDKs or recent versions of VS.

**Comment by brunotrevisan** [comment]
in 2021 I still can't run Opengl on Xbox the screen is black with hardware but it works perfectly on the computer, does anyone have any solutions?

**Comment by pinguin999** [comment]
We have OpenGL ES support in JNGL (https://github.com/jhasse/jngl) with Windows Universal App. But UWP is not supported on the new XBox generation.
