### ISSUE TITLE
How does ANGLE support Universal Windows Applications?

### ISSUE THREAD

**Issue by GuangBai** [microsoft/angle#62]
Hello All,

What does mean that ANGLE supports Universal Windows Applications?
Does this mean the ANGLE only supports OpenGL ES apps created with the UWP template recommended?
How should I migrate the Linux/Windows desktop OpenGL ES apps to UWP platforms (Windows 10 Mobile & Windows 10 IoT Core)?

Thank you,
Guang

**Comment by coopp** [comment]
Hi GuangBai,
  Universal Windows Applications are apps written for Windows in such a way that you can share code across multiple windows 10 devices.  Windows PC, Windows Phone, etc.  You write the application once and it gets compiled to run on the different platforms.
  For porting an existing application to Windows, the Visual Studio team created a starting template for ANGLE that may help you. You can find it here:
[Visual Studio 2015 Template that uses ANGLE](https://blogs.msdn.microsoft.com/vcblog/2015/07/30/cross-platform-code-sharing-with-visual-c/)

Hope this helps,
Thanks,
-Cooper

**Comment by GuangBai** [comment]
Hi Cooper,
Thank you for the info - I'd like to get more helps:
- How are these OpenGL ES2.0 apps deployed to the target? Use VC2015 or the App packages?
- Are ANGLE EGL & GLES dlls deployed to the target via App packages or copied over manually?
- Had you get the GLES apps running on Windows 10 IoT Core? Is there any compatibility issues?
  I'm able to build the ANGLE EGL and GLES dlls and got a sample GLES UWP running on Windows 10 TH2 (all bins were built with VC2015 update1), however, after deploying this app package to the Win10 IoT Core target via VC2015 update1, this GLES app just hangs the VC2015 update debug session.
  Regards,
  Guang

**Comment by coopp** [comment]
- Deploying applications to the target

During development, the most simple way to get an application to on the target is to use VS.  This should handle deployment and iterations of your application.  App Packages would work too but require additional steps.
- GLES dlls deployed with target

The GLES dlls will be deployed automatically because your project is using the NuGet package for ANGLE.  This handles referencing required binaries for you.
- Running on Windows 10 IoT Core builds

I need more information on this question.  Are you building ANGLE yourself?  You mentioned all bins were built with VS2015 update 1.  If you could provide additional information it would help me understand your scenario.  If you are manually copying ANGLE binaries to the target machine, you may want to switch to use the NuGet package and have that managed for you.  Mismatched ANGLE binaries for the target can cause hangs and possibly other issues during runtime.

**Comment by GuangBai** [comment]
I'm using latest "ms-master" source and building the ANGLE, GLES apps with it. There is no problem to deploy (VS2015 and App Package/WEBB) and run the GLES apps on my Windows 10 IoT Core TH2/DX11 target; however, the IoT Core TH2/DX12 target just hangs the VS2015 GLES remote debugging session before the "App:Initialize()" - I believe the ANGLE has problem to support the DX12 target.
BTW, which version/tag of ANGLE has good Khrono GLES2.0 conformance test results?

**Comment by GuangBai** [comment]
Hi Cooper,

I've got the "ms-master" ANGLE GLES20 running on the Windows 10 IoT Core TH2/DX12 target. My previous failure/hangs came from the dev system firewall issues. Now I'd like to sample some bench mark and Krono conformance quality and really would like to know which tag/version of "ms-master" is good...I noticed the ANGLE master v1.0.772 was certified with ES2.0.3 conformance in October 2011 - Do we have any level of conformance testing on "ms-master" recently?

Thank you,
Guang

**Comment by GuangBai** [comment]
Any update or feedbacks?
Thanks,
Guang

**Comment by coopp** [comment]
I am going to close this issue as it looks like your issue was resolved.

We are performing a merge of the latest Google master branch and ms-master this week.  This will bring in any additional fixes that have been made since our last merge.  We perform some conformance testing before checking in to ensure the quality of ms-master is high.  This testing isn't an official certification process.  Taking latest merges from Google master helps pick up new conformance-related fixes.  GLES20 support is solid.

**Comment by GuangBai** [comment]
Sorry for the late reply (vacations)...And Thank you for the update - I'll merge in your latest codes and initiate some conformance test.
