### ISSUE TITLE
Hololens Questions

### ISSUE THREAD

**Issue by mlfarrell** [microsoft/angle#75]
(please ignore my crazy avatar face)

@MikeRiches

A few questions about the sample app I noticed on the holo lens branch.
I noticed a lot of "for now"- style comments in the code related to the instancing and rtvId stuff.  
Are you guys eventually planning to automatically modify shader code and draw calls to automatically render to stereo targets?  Aka, a stereo-targeted glDrawElements call automatically becoming an instanced x 2 draw call with proper rtvId stuff being done automatically?  

One way it could be done automatically is to assume the modelViewMatrix contains an identity view.  Then you can assume its just the model matrix, prepend a system view matrix (holographic view transform), and offload the entire stereo rendering implementation out of OpenGL.  This is nice because it allows existing OpenGL games to be brought into hololens very quickly (essentially by just commenting out their camera transforms).

I only ask because I'm going to be starting some heavy development depending on this project soon and I'd like to know which parts of my workflow I should focus on and what will be temporary.

**Comment by mlfarrell** [comment]
Feel free to close this one. I asked this before I had a better understanding of how angle + hololens works.

**Comment by MikeRiches** [comment]
@mlfarrell: We just published an update that includes this feature. You can now enable a drawing mode that modifies the shader to draw in stereo; it works by providing your app with a mono view matrix that represents the holographic camera position, which the shader modifications undo before applying our holographic view/projection matrices. It also converts your draw call to the appropriate number of instances, even if it was not an instanced draw call to begin with. In this case, the projection matrix from your app should be set to identity, or eliminated from the pipeline. We chose to provide the view matrix so that you have a way to know where the eye vector should be.

**Comment by MikeRiches** [comment]
It's also worth noting that this feature is highly experimental - for example, you might currently run into problems with shadow maps.

**Comment by mlfarrell** [comment]
Great changes.  I just read through them.  Few questions before I pull your branch into mine.

Can you enable/disable the auto conversion stuff as you wish?  I have both 2D & 3D shaders

Are switching back & forth to non-stereo FBOs supported?

Can you make use of all the optimizations by disabling auto conversion and using gl_InstanceID directly?  This would help out my engine quite a bit which does now the conversion manually combined with glGet's of the stereo matrices.  

Is the ugly float hack used to set the RTV ID stuff gone?

**Comment by MikeRiches** [comment]
@mlfarrell, here are answers to your questions:
- It is not currently possible to toggle the drawing mode. To enable this, we should first implement a way to specify which shaders should be auto-converted as they are being loaded.
- Likewise, switching back and forth to non-stereo FBOs is not yet supported in auto-conversion mode because all shaders are currently being modified. Making the auto-conversion opt-in on a per-shader basis will make it possible to keep the 2D shaders intact, as well as other 3D shaders such as the shadow stencil shader.
- If you disable auto-conversion, and use shaders that are version 3 or higher, you can use gl_InstanceID directly in the same way that we do in ANGLE for the auto-conversion mode. This means that you avoid most of the ugly float hack used to set the RTV ID - although you must still pass the value to the pixel shader and assign it to a variable there so that ANGLE knows to retain it. Considering that your engine already does the conversion manually, and that you are using multi-pass rendering, I recommend doing it that way instead of using auto-conversion.
- Note that you can enable automatic image stabilization regardless of the drawing mode you choose.

**Comment by mlfarrell** [comment]
Well.. the fun thing is I probably now won't be using your auto conversion at all.  I'll actually prob remove the if-branch at the glDrawElements & friends calls to avoid the unnecessary overhead at that critical juncture.  

The instance ID thing is nice.  I'll be eventually using that for sure.  Once I can use it entirely and avoid any hacks in either shader stage, I'd like to pull those changes in.  

On my branch, I directly exposed the holographic focal point stuff and set it per frame using my engine directly.  

I also noticed a massive performance hit compared to D3D11 shaders likely caused by a combination of GL state sync overhead, non-VPRT (geometry shaders when not necessary), and lack of min16float support.  I had to bypass angle entirely to get past these performance problems.  It'd be nice to tackle the three issues here (well 2, since state sync is necessary) to get the performance up. 

sorry, I'm a tough customer I know :/
