### ISSUE TITLE
How to enable multisampling?

### ISSUE THREAD

**Issue by ergocortex** [microsoft/angle#84]
Hi, I want to enable multisampling (if it's possible) on OpenGLES 2 Application template.

How do i achieve it?, my first goal is Windows Universal  Plattform. Changing EGLConfig throws an exception.

  const EGLint configAttributes[] = 
    {
        EGL_RED_SIZE, 8,
        EGL_GREEN_SIZE, 8,
        EGL_BLUE_SIZE, 8,
        EGL_ALPHA_SIZE, 8,
        EGL_DEPTH_SIZE, 16,
        EGL_STENCIL_SIZE, 1,
    EGL_SAMPLE_BUFFERS, 1,
        EGL_SAMPLES, 4,  // This is for 4x MSAA.
        EGL_NONE
    };

Thank you in advance.

**Comment by austinkinross** [comment]
Hi there,

Currently ANGLE doesn't support multisampling this way. If you enumerate all of the valid EGLConfigs that the API returns (with the D3D11 renderer) then you'll see that they all have EGL_SAMPLES = 0.

One way to achieve multisampling in ANGLE is via this extension: https://www.khronos.org/registry/gles/extensions/ANGLE/ANGLE_framebuffer_multisample.txt

To use it, you would:
1. Create an MSAA renderbuffer via glRenderbufferStorageMultisampleANGLE
2. Bind the MSAA renderbuffer
3. Render your content onto the MSAA renderbuffer
4. Resolve the MSAA surface into a non-MSAA surface (e.g. your EGL surface) by calling glBlitFramebufferANGLE

This should work in OpenGL ES 2.0 contexts, but please not that this isn't supported on Windows Phone 8.0/8.1 era phones (i.e. devices that are D3D11 Feature Level 9_3). This is due to 9_3's lack of support for glBlitFramebufferANGLE. For these devices I recommend not enabling multisampling.

Hope this helps!
Austin

**Comment by austinkinross** [comment]
I believe this issue is resolved. Please feel free to reactivate the issue if you have further questions on this topic. Thanks!

**Comment by ergocortex** [comment]
Hello Austin, thank you for your response, it has led me to the solution, only for audience clarification, two issues :
- You cannot glBlitFramebufferANGLE from framebuffer with MSAA renderbuffer to default framebuffer, instead of it, you must to do two steps (1) glBlitFramebufferANGLE from framebuffer with MSAA renderbuffer to framebuffer with texture renderbuffer and (2) glBlitFramebufferANGLE from framebuffer with texture renderbuffer to default framebuffer.
- When rendering to framebuffer with MSAA renderbuffer y axis is flipped, so you must provide consequent vertical transformation of projection matrix.

Thank you.
