### ISSUE TITLE
glRotate

### ISSUE THREAD

**Issue by doginthehole** [microsoft/angle#98]
Hopefully this is a very simple question but I haven't been able to get glRotate() or glRoatatef() to work in project. It isn't being recognized as a function and I'm not sure where to go from here. Let me know if there's some includes that I'm not using or if I'm just an idiot.

**Comment by stevebest** [comment]
`glRotate`  and friends were once part of OpenGL fixed pipeline, but has been since removed from it, in favor of user-space matrix functions. Because ANGLE implements OpenGL ES 2.0, which features a fully programmable pipeline and is backwards incompatible with OpenGL ES 1.0, it has no such function.

Basically, you want to explicitly manipulate matrices that you provide to your shaders. You can implement the likes on `glRotate` in your own code, or better yet, grab one of the many existing solutions. In WebGL world (which is basically OpenGL ES 2.0 for JavaScript) a lot of people use [gl-matrix](https://github.com/toji/gl-matrix). Take a look to have a better idea on what it takes to rotate, translate, look at and perpectivize things in programmable pipeline.

**Comment by stevebest** [comment]
[GLM](https://github.com/g-truc/glm) is what you need.

**Comment by austinkinross** [comment]
Thanks Stepan for the great answer! 

doginthehole, feel free to reactivate this thread if you have further questions on this topic.
